---
- name: Initialize Fedora Workstation
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Set Fedora version variable
      set_fact:
        fedora_version: "{{ ansible_distribution_version }}"

    # install nvidia drivers
    # https://rpmfusion.org/Configuration
    # https://idroot.us/install-nvidia-drivers-fedora-42/
    - name: Install Free and Nonfree Repositories for RPM Fusion
      dnf:
        name: 
          - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm 
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
        state: present

    - name: Install NVIDIA drivers
      dnf:
        name:
          - akmod-nvidia
          - xorg-x11-drv-nvidia-cuda
          - xorg-x11-drv-nvidia-power # for suspend
        state: present

    - name: Enable nvidia-{suspend,resume,hibernate} services
      ansible.builtin.systemd:
        name: "nvidia-{{ item }}.service"
        enabled: yes
      loop:
        - suspend
        - resume
        - hibernate
    
    # install vscode (dnf)
    - name: Add Microsoft GPG key
      rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VS Code repository
      copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc

    - name: Install Visual Studio Code
      dnf:
        name: code
        state: present
    
    # install flatpaks
    - name: Install applications with flatpak
      community.general.flatpak:
        name: 
          - com.spotify.Client
          - io.github.celluloid_player.Celluloid
          - com.github.tchx84.Flatseal
        state: present
        


 



