---
- name: Initialize Fedora Workstation
  hosts: localhost
  connection: local
  become: yes
  vars:
    pyenv_root: "{{ ansible_env.HOME }}/.pyenv"
    current_user_name: "shan"
  tasks:

    - name: Run rpm command to get Fedora version
      command: rpm -E %fedora
      register: fedora_version

    - name: Display the Fedora version
      debug:
        msg: "Fedora version is {{ fedora_version.stdout }}"

    - name: Detect PCI devices
      ansible.builtin.command: lspci
      register: lspci_output
      changed_when: false
      failed_when: false

    - name: Install dnf-plugins-core
      dnf:
        name: dnf-plugins-core
        state: present

    # https://rpmfusion.org/Configuration
    - name: Install distribution-gpg-keys package
      ansible.builtin.dnf:
        name: distribution-gpg-keys
        state: present

    - name: Import RPM Fusion GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}"

    - name: Install RPM Fusion free release package
      ansible.builtin.dnf:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: false

    - name: Install Free and Nonfree Repositories for RPM Fusion
      dnf:
        name:
          - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm
        state: present

    # install codecs
    # https://rpmfusion.org/Howto/Multimedia
    - name: Swap ffmpeg-free with ffmpeg
      ansible.builtin.command:
        cmd: dnf swap ffmpeg-free ffmpeg --allowerasing -y
      become: true

    - name: Update multimedia group without weak deps and excluding PackageKit-gstreamer-plugin
      ansible.builtin.command:
        cmd: dnf update @multimedia --setopt=install_weak_deps=False --exclude=PackageKit-gstreamer-plugin -y
      become: true

    - import_tasks: tasks/nvidia.yaml
    - import_tasks: tasks/packages.yaml
    - import_tasks: tasks/development.yaml
