---
- name: Initialize Fedora Workstation
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  handlers:
    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
      become: true

  tasks:

    - name: Display the Fedora version
      ansible.builtin.debug:
        msg: "{{ ansible_facts['distribution_major_version'] }}"

    - name: Detect PCI devices
      ansible.builtin.command: lspci
      register: lspci_output
      changed_when: false
      failed_when: false

    - name: Install dnf-plugins-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
      become: true

    # install RPM Fusion repositories
    # https://rpmfusion.org/Configuration
    - name: Install Free and Nonfree Repositories for RPM Fusion
      ansible.builtin.dnf:
        name:
          - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm
        state: present
      become: true

    - ansible.builtin.import_tasks: tasks/codecs.yaml
    - ansible.builtin.import_tasks: tasks/nvidia.yaml
    - ansible.builtin.import_tasks: tasks/packages.yaml
    - ansible.builtin.import_tasks: tasks/vscode.yaml
    - ansible.builtin.import_tasks: tasks/brave.yaml
    - ansible.builtin.import_tasks: tasks/development.yaml
    - ansible.builtin.import_tasks: tasks/gnome-extensions.yaml
