# install brave origin browser
# https://brave.com/linux/
- name: Add Brave Beta repository
  ansible.builtin.get_url:
    url: https://brave-browser-rpm-beta.s3.brave.com/brave-browser-beta.repo
    dest: /etc/yum.repos.d/brave-browser-beta.repo
    mode: "0644"
  become: true

- name: Install Brave Origin browser
  ansible.builtin.dnf:
    name: brave-origin-beta
    state: present
    update_cache: true
  become: true
