# install packages (dnf)
- name: Install minimal packages with dnf
  ansible.builtin.dnf:
    name:
      - gnome-tweaks
      - ffmpegthumbnailer
      - libreoffice-writer
      - libreoffice-calc
      - vlc
    state: present
  become: true

# remove packages (dnf)
- name: Remove packages with dnf
  ansible.builtin.dnf:
    name:
      - gnome-tour
      - gnome-contacts
      - gnome-maps
      - gnome-weather
      - yelp
      - gnome-fonts
      - gnome-characters
      - gnome-connections
      - gnome-boxes
      - mediawriter
      - totem # gnome's default video player
      - showtime # gnome's default audio player
      - malcontent # parental content
      # - simple-scan # document scanner
    state: absent
  become: true

# install flatpaks
- name: Add the Flathub flatpak remote repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
  become: true

- name: Install minimal applications with flatpak
  community.general.flatpak:
    name:
      - com.spotify.Client
      # - io.mpv.Mpv
      - com.github.tchx84.Flatseal
      - org.gnome.Extensions
    state: present

- name: Install extra applications with flatpak
  community.general.flatpak:
    name:
      - org.gimp.GIMP
      - it.mq1.TinyWiiBackupManager
      - net.pcsx2.PCSX2
      - com.github.qarmin.czkawka
    state: present
  tags: extras