# install packages (dnf)
- name: Install packages with dnf
  dnf:
    name:
      - gnome-tweaks
      - ffmpegthumbnailer
      - libreoffice-writer
      - libreoffice-calc
      - vlc
      - python3-pip
    state: present
  become: yes

# remove packages (dnf)
- name: Remove packages with dnf
  dnf:
    name:
      - gnome-tour
      - gnome-contacts
      - gnome-maps
      - gnome-weather
      - yelp
      - gnome-fonts
      - gnome-characters
      - gnome-connections
      - gnome-boxes
      - mediawriter 
      # - simple-scan # document scanner
    state: absent
  become: yes

# install flatpaks   
- name: Add the Flathub flatpak remote repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
  become: yes

- name: Install applications with flatpak
  community.general.flatpak:
    name:
      - com.spotify.Client
      - org.gimp.GIMP
      - io.mpv.Mpv
      - com.github.tchx84.Flatseal
      - org.gnome.Extensions
      - it.mq1.TinyWiiBackupManager
      - net.pcsx2.PCSX2
      - com.github.qarmin.czkawka
    state: present

